web:
  dockerfile: Dockerfile-php
  build: infrastructure
  ports:
    - "8080:80"
  volumes:
    - ./www:/var/www/html
    - ./infrastructure/vhost.conf:/etc/httpd/conf.d/001-default.conf
    - ./infrastructure/log/:/var/log/apache2/
  links:
    - db
db:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_ROOT_PASSWORD=dbpass
